name: Periodic Rebase

on:
  push:
    branches: bundle/it-wallet

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Rebase master branch
        run: |
          git config --global user.email "mario.perrotta@pagopa.it"
          git config --global user.name "hevelius"
          git fetch origin
          git rebase origin/main
