name: Release locales on CDN

on:
  pull_request: #added to register workflow
  # push:
  #   branches:
  #     - IOPLT-1318-GHA-release-locales # to be switched to master
  #   paths-ignore:
  #     - "CODEOWNERS"
  #     - "**.md"
  #     - ".**"

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:

  publish:
    name: Release locales to production assets CDN
    runs-on: ubuntu-24.04
    environment: prod-cd
    permissions:
      id-token: write
      pull-requests: write
    env:
      EXCLUDED_PATTERN: 'README.md;.gitignore;'
      EXCLUDED_PATH: ''
      FILES_TO_COPY: '*.json'
      REPOSITORY_PATH: 'locales'
      STORAGE_ACCOUNT_NAME: 'iopitnassetsst01'
      STORAGE_ACCOUNT_CONTAINER: '$web'
      STORAGE_ACCOUNT_PATH: 'locales'
      CDN_PROFILE_NAME: 'io-p-itn-assets-afd-01'
      CDN_ENDPOINT: 'io-p-itn-assets-fde-01-befjajf6hjg9ajem.a01.azurefd.net'
      CDN_RESOURCE_GROUP: 'io-p-itn-assets-cdn-rg-01'
      CDN_PURGE_DOMAINS: 'assets.io.pagopa.it'

    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Azure Login
        id: az_login
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_CD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        id: storage_upload
        run: |
            az storage copy \
              --account-name "$STORAGE_ACCOUNT_NAME" \
              --destination-container "$STORAGE_ACCOUNT_CONTAINER" \
              --source './$REPOSITORY_PATH' \
              --include-pattern "$FILES_TO_COPY"
              --exclude-pattern "$EXCLUDED_PATTERN" \
              --exclude-path "$EXCLUDED_PATH" \
              --recursive
     
      - name: Purge AFD locales endpoint
        run: |
            az afd endpoint purge \
              --content-paths '/$STORAGE_ACCOUNT_PATH/*' \
              --profile-name "$CDN_PROFILE_NAME" \
              --endpoint-name "$CDN_ENDPOINT" \
              --domains "$CDN_PURGE_DOMAINS" \
              --resource-group "$CDN_RESOURCE_GROUP"

      - name: Azure Logout
        id: az_logout
        if: always()
        run: |
          az logout